version: '3.7'

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  redis:
    image: redis:5.0.6
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    ports:
      - 9000:9000
    command: --compat server /data
  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025:8025
      - 1025:1025
networks:
  default:
    name: example-chat-network
